// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Redirect struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Redirect) Reset()         { *m = Redirect{} }
func (m *Redirect) String() string { return proto.CompactTextString(m) }
func (*Redirect) ProtoMessage()    {}
func (*Redirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Redirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect.Unmarshal(m, b)
}
func (m *Redirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect.Marshal(b, m, deterministic)
}
func (m *Redirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect.Merge(m, src)
}
func (m *Redirect) XXX_Size() int {
	return xxx_messageInfo_Redirect.Size(m)
}
func (m *Redirect) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect proto.InternalMessageInfo

func (m *Redirect) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Redirect) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Redirect) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Redirect)(nil), "protobuf.Redirect")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69,
	0x4a, 0x7e, 0x5c, 0x1c, 0x41, 0xa9, 0x29, 0x99, 0x45, 0xa9, 0xc9, 0x25, 0x42, 0x42, 0x5c, 0x2c,
	0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17,
	0x73, 0x69, 0x51, 0x8e, 0x04, 0x13, 0x58, 0x08, 0xc4, 0x14, 0x92, 0xe1, 0xe2, 0x4c, 0x2e, 0x4a,
	0x4d, 0x2c, 0x49, 0x4d, 0x71, 0x2c, 0x91, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0e, 0x42, 0x08, 0x18,
	0x15, 0x73, 0x09, 0x04, 0x67, 0xe4, 0x17, 0x95, 0xa4, 0xe6, 0xa5, 0x16, 0x05, 0x43, 0xec, 0x14,
	0xd2, 0xe7, 0x62, 0x0d, 0x2e, 0xc9, 0x2f, 0x4a, 0x15, 0x12, 0xd2, 0x83, 0xd9, 0xab, 0x07, 0xb3,
	0x54, 0x0a, 0x8b, 0x98, 0x90, 0x1e, 0x17, 0x8b, 0x5b, 0x66, 0x5e, 0x0a, 0xb1, 0xea, 0x93, 0xd8,
	0xc0, 0x42, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0x1c, 0x77, 0xa5, 0xe6, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShortenerServiceClient is the client API for ShortenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortenerServiceClient interface {
	Store(ctx context.Context, in *Redirect, opts ...grpc.CallOption) (*Redirect, error)
	Find(ctx context.Context, in *Redirect, opts ...grpc.CallOption) (*Redirect, error)
}

type shortenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerServiceClient(cc grpc.ClientConnInterface) ShortenerServiceClient {
	return &shortenerServiceClient{cc}
}

func (c *shortenerServiceClient) Store(ctx context.Context, in *Redirect, opts ...grpc.CallOption) (*Redirect, error) {
	out := new(Redirect)
	err := c.cc.Invoke(ctx, "/protobuf.ShortenerService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerServiceClient) Find(ctx context.Context, in *Redirect, opts ...grpc.CallOption) (*Redirect, error) {
	out := new(Redirect)
	err := c.cc.Invoke(ctx, "/protobuf.ShortenerService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServiceServer is the server API for ShortenerService service.
type ShortenerServiceServer interface {
	Store(context.Context, *Redirect) (*Redirect, error)
	Find(context.Context, *Redirect) (*Redirect, error)
}

// UnimplementedShortenerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShortenerServiceServer struct {
}

func (*UnimplementedShortenerServiceServer) Store(ctx context.Context, req *Redirect) (*Redirect, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedShortenerServiceServer) Find(ctx context.Context, req *Redirect) (*Redirect, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterShortenerServiceServer(s *grpc.Server, srv ShortenerServiceServer) {
	s.RegisterService(&_ShortenerService_serviceDesc, srv)
}

func _ShortenerService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Redirect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ShortenerService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).Store(ctx, req.(*Redirect))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Redirect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ShortenerService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).Find(ctx, req.(*Redirect))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShortenerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ShortenerService",
	HandlerType: (*ShortenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _ShortenerService_Store_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _ShortenerService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
