// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//protoc --proto_path=protobuf --proto_path=../../../../tool   --go_out=plugins=grpc:protobuf protobuf/service.proto
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RedirectFindRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectFindRequest) Reset()         { *m = RedirectFindRequest{} }
func (m *RedirectFindRequest) String() string { return proto.CompactTextString(m) }
func (*RedirectFindRequest) ProtoMessage()    {}
func (*RedirectFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RedirectFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectFindRequest.Unmarshal(m, b)
}
func (m *RedirectFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectFindRequest.Marshal(b, m, deterministic)
}
func (m *RedirectFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectFindRequest.Merge(m, src)
}
func (m *RedirectFindRequest) XXX_Size() int {
	return xxx_messageInfo_RedirectFindRequest.Size(m)
}
func (m *RedirectFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectFindRequest proto.InternalMessageInfo

func (m *RedirectFindRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RedirectFindResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectFindResponse) Reset()         { *m = RedirectFindResponse{} }
func (m *RedirectFindResponse) String() string { return proto.CompactTextString(m) }
func (*RedirectFindResponse) ProtoMessage()    {}
func (*RedirectFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *RedirectFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectFindResponse.Unmarshal(m, b)
}
func (m *RedirectFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectFindResponse.Marshal(b, m, deterministic)
}
func (m *RedirectFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectFindResponse.Merge(m, src)
}
func (m *RedirectFindResponse) XXX_Size() int {
	return xxx_messageInfo_RedirectFindResponse.Size(m)
}
func (m *RedirectFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectFindResponse proto.InternalMessageInfo

func (m *RedirectFindResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RedirectFindResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type RedirectStoreRequest struct {
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectStoreRequest) Reset()         { *m = RedirectStoreRequest{} }
func (m *RedirectStoreRequest) String() string { return proto.CompactTextString(m) }
func (*RedirectStoreRequest) ProtoMessage()    {}
func (*RedirectStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *RedirectStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectStoreRequest.Unmarshal(m, b)
}
func (m *RedirectStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectStoreRequest.Marshal(b, m, deterministic)
}
func (m *RedirectStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectStoreRequest.Merge(m, src)
}
func (m *RedirectStoreRequest) XXX_Size() int {
	return xxx_messageInfo_RedirectStoreRequest.Size(m)
}
func (m *RedirectStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectStoreRequest proto.InternalMessageInfo

func (m *RedirectStoreRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type RedirectStoreResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectStoreResponse) Reset()         { *m = RedirectStoreResponse{} }
func (m *RedirectStoreResponse) String() string { return proto.CompactTextString(m) }
func (*RedirectStoreResponse) ProtoMessage()    {}
func (*RedirectStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *RedirectStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectStoreResponse.Unmarshal(m, b)
}
func (m *RedirectStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectStoreResponse.Marshal(b, m, deterministic)
}
func (m *RedirectStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectStoreResponse.Merge(m, src)
}
func (m *RedirectStoreResponse) XXX_Size() int {
	return xxx_messageInfo_RedirectStoreResponse.Size(m)
}
func (m *RedirectStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectStoreResponse proto.InternalMessageInfo

func (m *RedirectStoreResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RedirectStoreResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*RedirectFindRequest)(nil), "protobuf.RedirectFindRequest")
	proto.RegisterType((*RedirectFindResponse)(nil), "protobuf.RedirectFindResponse")
	proto.RegisterType((*RedirectStoreRequest)(nil), "protobuf.RedirectStoreRequest")
	proto.RegisterType((*RedirectStoreResponse)(nil), "protobuf.RedirectStoreResponse")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69,
	0x4a, 0x9a, 0x5c, 0xc2, 0x41, 0xa9, 0x29, 0x99, 0x45, 0xa9, 0xc9, 0x25, 0x6e, 0x99, 0x79, 0x29,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x0d, 0x97, 0x08, 0xaa, 0xd2, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x6c, 0x6a, 0x85, 0x04, 0xb8, 0x98, 0x4b, 0x8b, 0x72, 0x24, 0x98, 0xc0,
	0x42, 0x20, 0xa6, 0x92, 0x06, 0x42, 0x77, 0x70, 0x49, 0x7e, 0x51, 0x2a, 0xcc, 0x26, 0x4c, 0x95,
	0xb6, 0x5c, 0xa2, 0x68, 0x2a, 0x49, 0xb1, 0xc8, 0x68, 0x31, 0x23, 0x97, 0x40, 0x70, 0x46, 0x7e,
	0x51, 0x49, 0x6a, 0x5e, 0x6a, 0x51, 0x30, 0xc4, 0xdb, 0x42, 0x1e, 0x5c, 0xac, 0x60, 0xb3, 0x84,
	0xe4, 0xf4, 0x60, 0x5e, 0xd7, 0xc3, 0xe6, 0x1c, 0x29, 0x79, 0x9c, 0xf2, 0x50, 0x47, 0xb8, 0x72,
	0xb1, 0x80, 0x7c, 0x2f, 0x24, 0x8b, 0xa9, 0x10, 0x29, 0x00, 0xa5, 0xe4, 0x70, 0x49, 0x43, 0x8c,
	0x49, 0x62, 0x03, 0x4b, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xa1, 0x1e, 0x97, 0x99,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShortenerServiceClient is the client API for ShortenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortenerServiceClient interface {
	Store(ctx context.Context, in *RedirectStoreRequest, opts ...grpc.CallOption) (*RedirectStoreResponse, error)
	Find(ctx context.Context, in *RedirectFindRequest, opts ...grpc.CallOption) (*RedirectFindResponse, error)
}

type shortenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerServiceClient(cc grpc.ClientConnInterface) ShortenerServiceClient {
	return &shortenerServiceClient{cc}
}

func (c *shortenerServiceClient) Store(ctx context.Context, in *RedirectStoreRequest, opts ...grpc.CallOption) (*RedirectStoreResponse, error) {
	out := new(RedirectStoreResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ShortenerService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerServiceClient) Find(ctx context.Context, in *RedirectFindRequest, opts ...grpc.CallOption) (*RedirectFindResponse, error) {
	out := new(RedirectFindResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ShortenerService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServiceServer is the server API for ShortenerService service.
type ShortenerServiceServer interface {
	Store(context.Context, *RedirectStoreRequest) (*RedirectStoreResponse, error)
	Find(context.Context, *RedirectFindRequest) (*RedirectFindResponse, error)
}

// UnimplementedShortenerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShortenerServiceServer struct {
}

func (*UnimplementedShortenerServiceServer) Store(ctx context.Context, req *RedirectStoreRequest) (*RedirectStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedShortenerServiceServer) Find(ctx context.Context, req *RedirectFindRequest) (*RedirectFindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterShortenerServiceServer(s *grpc.Server, srv ShortenerServiceServer) {
	s.RegisterService(&_ShortenerService_serviceDesc, srv)
}

func _ShortenerService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ShortenerService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).Store(ctx, req.(*RedirectStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ShortenerService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).Find(ctx, req.(*RedirectFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShortenerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ShortenerService",
	HandlerType: (*ShortenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _ShortenerService_Store_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _ShortenerService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
